---
version: '3.7'

services:
  osrm_colombia:
    image: colombia_osrm
    build:
      context: .
      dockerfile: ./docker/colombia.dockerfile
    ports:
      - "5000:5000"
  osrm_turkey:
    image: turkey_osrm
    build:
      context: .
      dockerfile: ./docker/turkey.dockerfile
    ports:
      - "5000:5000"